version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - echo Setting file permissions...
      - chmod +x scripts/*.sh
      - echo Build completed...

artifacts:
  files:
    - appspec.yml
    - scripts/before_install.sh
    - index.html
  discard-paths: no
